select b.TITLE, b.BOARD_ID, r.REPLY_ID, 
    r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
from USED_GOODS_BOARD b, USED_GOODS_REPLY r
where DATE(b.CREATED_DATE) BETWEEN '2022-10-01' AND '2022-10-31'
    AND b.BOARD_ID = r.BOARD_ID
ORDER BY r.CREATED_DATE, b.TITLE