SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b, USED_GOODS_USER u
WHERE b.WRITER_ID = u.user_id AND b.status ="DONE"
GROUP BY WRITER_ID
HAVING sum(b.PRICE) >= 700000
ORDER BY sum(b.PRICE)
