SELECT concat("/home", "/grep", "/src/", f.BOARD_ID, "/", f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD b, USED_GOODS_FILE f
WHERE b.BOARD_ID = f.BOARD_ID
    AND b.views = (SELECT max(views) FROM USED_GOODS_BOARD)
ORDER BY f.FILE_ID DESC